use_frameworks!

target 'InstagramAPI_Example' do
  pod 'InstagramAPI', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'InstagramAPI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
